AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  runTwitterBot:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: sparrow_kms.handler
      Runtime: python2.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::870564031584:role/service-role/Lambda-Execution-with-KMS-Descryption
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
